// Phase B smoke app: exercises View / Text / Button / event dispatch
// without the JSX → C++ pipeline. Real apps generated by geatsc will
// drop into targets/macos/generated/<app>/ and supersede this.

#include "ui/document.h"
#include "events.h"
#include <cstdio>

namespace {
gea::embedded::ui::TextElement g_counterLabel;
int g_counterValue = 0;

void refreshCounterLabel()
{
	char buf[32];
	std::snprintf(buf, sizeof(buf), "Clicked %d", g_counterValue);
	g_counterLabel.setText(buf);
}
}  // namespace

extern "C" {

void gea_embedded_app_init(int width, int height)
{
	using namespace gea::embedded::ui;
	using gea::framework::events::PointerEvent;

	auto &doc = Document::instance();
	doc.clear();
	auto root = doc.createView();
	root.style().backgroundColor(0x33DE);  // RGB565 ~ #3478F6
	root.style().set(Property::FlexDirection, 0);   // column
	root.style().set(Property::JustifyContent, 1);  // center
	root.style().set(Property::AlignItems, 1);      // center
	root.style().set(Property::Gap, 16);

	auto title = doc.createText("Hello, native Mac!");
	title.style().color(0xFFFF);     // white
	title.style().set(Property::FontSize, 24);
	root.appendChild(title);

	g_counterLabel = doc.createText("Clicked 0");
	g_counterLabel.style().color(0xFFFF);
	g_counterLabel.style().set(Property::FontSize, 16);
	root.appendChild(g_counterLabel);
	g_counterValue = 0;

	auto button = doc.createButton();
	auto buttonLabel = doc.createText("Click me");
	button.appendChild(buttonLabel);
	button.addEventListener("click", [](PointerEvent &) {
		g_counterValue++;
		refreshCounterLabel();
	});
	root.appendChild(button);

	doc.mount(root, width, height);
}

void gea_embedded_app_frame(int timestampMs)
{
	(void)timestampMs;
}

}  // extern "C"
